@extends('front-end.layouts.app3')
@section('titulo')
<title>Propitech - Terminos y condiciones de nuestra web</title>
@endsection
@section('meta')
<meta name="description" content="Terminos y condiciones">
<meta name="author" content="benjaminperez.cl">
<meta name="generator" content="LaravelV7">
@endsection
@section('css')
    <style>
        p 
        {
            margin-bottom: 0px !important;
        }
    </style>
@endsection
@section('content')
<section class="pt-4">
    <h2 class="fs-32 lh-16 text-dark text-center">Terminos y condiciones</h2>
    <div class="collapse-tabs">
        <div class="tab-content shadow-none rounded-0 pt-8 pb-10 pb-md-12 px-0 bg-gray-01">
            <div class="container">
                <p><strong>1.-</strong> <strong>Objeto.</strong></p>
                <p>&nbsp;</p>
                <p>Los presentes T&eacute;rminos y Condiciones Generales de Uso (en adelante, los "T&eacute;rminos y Condiciones") regulan el uso de del sitio web <a href="http://www.propitech.cl">www.propitech.cl</a> (en adelante, el "Sitio Web"), ya sea con su actual nombre o con cualquier otra denominaci&oacute;n con la que pueda figurar en el futuro. El Sitio Web es propiedad de <strong>INVERSIONES Y SERVICIOS PROFESIONALES B&amp;C SpA</strong>, rol &uacute;nico tributario n&uacute;mero 77.135.302-9, con domicilio en Avenida Providencia N&ordm; 1208, Oficina N&ordm; 207, comuna de Providencia, ciudad de Santiago, Regi&oacute;n Metropolitana, y direcci&oacute;n de correo electr&oacute;nico <u>contacto@propitech.cl</u> (en adelante &ldquo;Propitech by Cirobu&rdquo;).</p>
                <p>&nbsp;</p>
                <p>Al acceder y utilizar el Sitio Web, usted (en adelante, el "Usuario") reconoce que ha le&iacute;do y aceptado estos T&eacute;rminos y Condiciones y se compromete a cumplir con todo lo aqu&iacute; estipulado. Asimismo, el Usuario reconoce y acepta que el acceso y uso del Sitio Web estar&aacute; sujeto a los T&eacute;rminos y Condiciones que se encuentren vigentes al momento en que acceda al mismo. Propitech by Cirobu se reserva el derecho de modificar en cualquier momento los presentes T&eacute;rminos y Condiciones con pleno respeto a las leyes que regulan el consumo de bienes y servicios en Chile, as&iacute; como cualesquiera otras condiciones generales o particulares que resulten de aplicaci&oacute;n. Asimismo, Propitech by Cirobu se reserva el derecho de suspender, interrumpir o dejar de operar el Sitio Web en cualquier momento.</p>
                <p>&nbsp;</p>
                <p>Al momento de pulsar el bot&oacute;n "Acepto", en la p&aacute;gina web de Propitech by Cirobu, los presentes T&eacute;rminos y Condiciones ser&aacute;n vinculantes y obligar&aacute;n al Usuario para todos los efectos legales a que haya lugar, a la vez de que se acepta expresamente que Propitech by Cirobu pueda facilitar los datos que sean necesarios a terceros que presten el servicio de manejo de login, claves y otros relacionados al ingreso al Sitio Web, los que deber&aacute;n ser tratados por el prestador de servicios con los m&aacute;s altos est&aacute;ndares de protecci&oacute;n de datos.</p>
                <p>&nbsp;</p>
                <p><strong>2.- Contenidos.</strong></p>
                <p>&nbsp;</p>
                <p>A trav&eacute;s del Sitio Web, Propitech by Cirobu facilita al Usuario un servicio de corretaje de propiedades, recaudaci&oacute;n, administraci&oacute;n del contrato de arriendo, cobranza y anticipo (cuando corresponda) de renta de arriendo (en adelante, los "Servicios"), reparaci&oacute;n y arreglo de propiedades y construcci&oacute;n. El Sitio Web facilita al Usuario el acceso a diversos contenidos, informaci&oacute;n y datos proporcionados por Propitech by Cirobu en relaci&oacute;n con los Servicios (en adelante, los "Contenidos"). Propitech by Cirobu se reserva el derecho a modificar en cualquier momento la presentaci&oacute;n y la configuraci&oacute;n del Sitio Web, as&iacute; como las correspondientes condiciones de acceso y uso. Propitech by Cirobu no garantiza que los Contenidos proporcionados a trav&eacute;s del Sitio Web ser&aacute;n en todo caso correctos, completos o actualizados, informaci&oacute;n que depender&aacute; de lo que informen los usuarios a Propitech by Cirobu al momento de publicar sus propiedades en el Sitio Web.&nbsp;</p>
                <p>&nbsp;</p>
                <p><strong>3.- Acceso y Uso.</strong></p>
                <p>&nbsp;</p>
                <p>El acceso al Sitio Web est&aacute; limitado a mayores de 18 a&ntilde;os. No obstante, lo anterior, el acceso a determinados contenidos y/o participaci&oacute;n en las promociones de Propitech by Cirobu puede estar limitado a menores emancipados o debidamente representados por quien la ley designe en tal calidad, seg&uacute;n se indique en cada caso. Con car&aacute;cter general, el Usuario podr&aacute; acceder al Sitio Web de forma libre y gratuita. El Usuario reconoce y acepta que el acceso y uso del Sitio Web tiene lugar libre y conscientemente, bajo su exclusiva responsabilidad. Propitech by Cirobu no ser&aacute; en ning&uacute;n caso responsable del uso que el Usuario y/o terceros pudieran hacer del Sitio Web ni de los da&ntilde;os y perjuicios que pudieran derivarse del mismo.</p>
                <p>&nbsp;</p>
                <p>El Usuario se compromete a hacer un uso adecuado y l&iacute;cito del Sitio Web de conformidad con la legislaci&oacute;n aplicable, los presentes T&eacute;rminos y Condiciones, la moral, buenas costumbres y el orden p&uacute;blico. El Usuario deber&aacute; abstenerse de (i) hacer un uso no autorizado o fraudulento del Sitio Web; (ii) acceder o intentar acceder a recursos restringidos del Sitio Web; (iii) utilizar el Sitio Web con fines o efectos il&iacute;citos, ilegales, contrarios a lo establecido en los presentes T&eacute;rminos y Condiciones, a la buena fe, la moral, las buenas costumbres y al orden p&uacute;blico, lesivos de los derechos e intereses de terceros, o que de cualquier forma puedan da&ntilde;ar, inutilizar, sobrecargar o impedir la normal utilizaci&oacute;n del Sitio Web; (iv) provocar da&ntilde;os en el Sitio Web o en los sistemas de sus proveedores o de terceros; (v) introducir o difundir virus inform&aacute;ticos o cualesquiera otros sistemas f&iacute;sicos o l&oacute;gicos que sean susceptibles de provocar da&ntilde;os en los sistemas de Propitech by Cirobu, de sus proveedores o de terceros, (vi) intentar acceder, utilizar y/o manipular los datos de Propitech by Cirobu, terceros proveedores y otros usuarios; (vii) reproducir o copiar, distribuir, permitir el acceso del p&uacute;blico a trav&eacute;s de cualquier modalidad de comunicaci&oacute;n p&uacute;blica, transformar o modificar los Contenidos y/o el Sitio Web, a menos que se cuente con la autorizaci&oacute;n del titular de los correspondientes derechos o ello est&eacute; legalmente permitido; (viii) obtener o intentar obtener los Contenidos empleando para ello medios o procedimientos distintos de los que se hayan puesto a su disposici&oacute;n a este efecto en el Sitio Web.</p>
                <p>&nbsp;</p>
                <p>En caso que el Usuario incumpla con el uso adecuado y l&iacute;cito del Sitio Web, de acuerdo a los par&aacute;metros antes se&ntilde;alados, Propitech by Cirobu podr&aacute; bloquear unilateralmente de forma temporal o definitiva su cuenta, sin derecho a indemnizaci&oacute;n alguna en favor del Usuario. Adem&aacute;s, Propitech by Cirobu tendr&aacute; derecho a ser resarcido por el Usuario de todos los perjuicios que dicho uso inadecuado o il&iacute;cito del Sitio Web les hubiera ocasionado.</p>
                <p>&nbsp;</p>
                <p>El Usuario &uacute;nicamente podr&aacute; acceder al Sitio Web a trav&eacute;s de los medios autorizados.</p>
                <p>&nbsp;</p>
                <p><strong>4.- Condiciones Adicionales para el Acceso y Uso.</strong></p>
                <p>&nbsp;</p>
                <p>&nbsp;</p>
                <p>El acceso y uso del Sitio Web estar&aacute; sujeto en todo caso al previo registro del Usuario mediante la cumplimentaci&oacute;n del correspondiente formulario ("Formulario de Registro"), que ser&aacute; previamente facilitado digitalmente al Usuario, debiendo &eacute;ste completar todos los antecedentes que revisten el car&aacute;cter de obligatorios. Propitech by Cirobu podr&iacute;a negar el Registro de un Usuario si, a su juicio, no cumple con los T&eacute;rminos y Condiciones, Pol&iacute;tica de Privacidad de Propitech by Cirobu y dem&aacute;s disposiciones pertinentes. Los datos introducidos por el Usuario en el Formulario de Registro deber&aacute;n ser exactos, actuales y veraces en todo momento. Propitech by Cirobu se reserva el derecho de eliminar y/o bloquear de forma temporal o definitiva la cuenta de un Usuario, que haya accedido a la misma a trav&eacute;s de la entrega del Formulario de Registro con informaci&oacute;n inexacta, desactualizada o falsa, cuando sea Propitech by Cirobu tome conocimiento de alguno de dichos hechos.</p>
                <p>&nbsp;</p>
                <p>El acceso y uso del Sitio Web estar&aacute; sujeto una contrase&ntilde;a que el Usuario crea al momento de rellenar el Formulario de Registro. Cuando se ingrese al Sitio Web utilizando la contrase&ntilde;a antes se&ntilde;alada, el acceso se reputar&aacute; realizado por el Usuario que tiene dicha contrase&ntilde;a, quien responder&aacute; en todo caso de tal acceso y uso. El Usuario ser&aacute; responsable en todo momento de la custodia de su contrase&ntilde;a, asumiendo, en consecuencia, cualesquiera da&ntilde;os y perjuicios que pudieran derivarse de su uso indebido, as&iacute; como de la cesi&oacute;n, revelaci&oacute;n o extrav&iacute;o de la misma. En caso de olvido de la contrase&ntilde;a o cualquier otra circunstancia que suponga un riesgo de acceso y/o utilizaci&oacute;n por parte de terceros no autorizados, el Usuario lo comunicar&aacute; inmediatamente a Propitech by Cirobu a fin de que &eacute;ste proceda inmediatamente al bloqueo y sustituci&oacute;n de la misma (el proceso de sustituci&oacute;n de contrase&ntilde;a seguir&aacute; el mismo procedimiento que para la contrase&ntilde;a original). As&iacute;, cualesquiera operaciones realizadas antes de dicha comunicaci&oacute;n se reputar&aacute;n efectuadas por el Usuario, quien ser&aacute; responsable y pagar&aacute; los gastos y/o da&ntilde;os que se deriven de cualquier acceso y/o uso no autorizado que se realice con anterioridad a dicha comunicaci&oacute;n.</p>
                <p><strong>&nbsp;</strong></p>
                <p><strong>5.- Relaci&oacute;n Contractual y Precio del Servicio.</strong></p>
                <p>&nbsp;</p>
                <p>El Usuario (incluyendo potenciales arrendatarios), declara que a partir del momento en que acepta estos T&eacute;rminos y Condiciones a trav&eacute;s del Sitio Web, queda totalmente obligado por los mismos de acuerdo a lo se&ntilde;alado en este documento.</p>
                <p>El Usuario que solo use el Sitio Web para la corredur&iacute;a de propiedades, solamente estar&aacute; obligado por estos T&eacute;rminos y Condiciones.</p>
                <p>&nbsp;</p>
                <p>Asimismo, al contratar los Servicios, el Usuario celebrar&aacute; un contrato de mandato con Propitech by Cirobu (el &ldquo;Mandato&rdquo;), en el cual se detallar&aacute;n, entre otras cosas, los derechos y obligaciones del Usuario en relaci&oacute;n a los Servicios, las facultades que se entregar&aacute;n a Propitech by Cirobu para la prestaci&oacute;n de los Servicios y la remuneraci&oacute;n que el Usuario deber&aacute; pagar por los mismos. Dicha remuneraci&oacute;n ascender&aacute; a un porcentaje del valor de la renta de arrendamiento anual del respectivo contrato de arrendamiento u otro valor, seg&uacute;n el detalle que se incluir&aacute; para cada caso en el Anexo de Condiciones Particulares del referido Mandato, dependiendo del plan que hubiera decidido contratar el Usuario. Se deja constancia que los planes disponibles, los servicios que comprenden y su respectivo precio, se encuentran publicados en el Sitio Web en la secci&oacute;n &ldquo;Precios&rdquo;, los que se dan por &iacute;ntegramente reproducidos en estos T&eacute;rminos y Condiciones y se consideran parte integrante de los mismos. El precio por los Servicios, independiente cual sea su valor, podr&aacute; ser pagado mediante los medios de pago debidamente informados en el Sitio Web, dejando constancia que dicho precio podr&aacute; ser pagado en cuotas, siempre y cuando sea efectuado mediante tarjeta de cr&eacute;dito o un pago autom&aacute;tico a trav&eacute;s del correspondiente descuento del pago del arriendo, si as&iacute; se hubiere pactado.</p>
                <p>&nbsp;</p>
                <p>Ser&aacute; responsabilidad del Usuario informar a Propitech by Cirobu si el inmueble se pretende arrendar amoblado, para efectos de que el respectivo contrato de arrendamiento se ajuste en lo que corresponda. Se deja constancia que, de conformidad a la legislaci&oacute;n chilena, el arriendo de inmuebles amoblados se encuentra afecto al pago de IVA, siendo responsabilidad exclusiva del Usuario efectuar la declaraci&oacute;n y pago de dicho impuesto y cumplir con cualquier otra obligaci&oacute;n relacionada a &eacute;ste frente al SII, no cabi&eacute;ndole responsabilidad alguna a Propitech by Cirobu al respecto.</p>
                <p>&nbsp;</p>
                <p>Propitech by Cirobu no realizar&aacute; transacciones de reversa con respecto a los montos recaudados, es decir, el Usuario no podr&aacute; anular las recaudaciones ya realizadas por Propitech by Cirobu o por un tercero que se subcontrate al efecto.</p>
                <p>&nbsp;</p>
                <p>Con arreglo a lo dispuesto en la Pol&iacute;tica de Privacidad los datos de la tarjeta de cr&eacute;dito facilitados en el Formulario de Registro, cuando corresponda, ser&aacute;n remitidos a la empresa proveedora de pagos y encargada de almacenar dichos datos del Usuario, a lo cual el Usuario consiente expresamente al momento de aceptar estos T&eacute;rminos y Condiciones en la forma previamente se&ntilde;alada. El Usuario deber&aacute; acceder o podr&aacute; ser redirigido al sitio web del proveedor de pagos a trav&eacute;s del enlace facilitado al efecto en el Formulario de Registro. En todo caso, se recomienda al Usuario consultar los t&eacute;rminos y condiciones de uso y las pol&iacute;ticas de privacidad de los sitios web de terceros a los que accedan a trav&eacute;s de enlaces incluidos en el Sitio Web ya que Propitech by Cirobu no es responsable por dichas pol&iacute;ticas de privacidad, como se establece en la Pol&iacute;tica de Privacidad de Propitech by Cirobu.</p>
                <p>&nbsp;</p>
                <p>Por motivos de seguridad no est&aacute; permitido utilizar un mismo m&eacute;todo de pago en m&aacute;s de dos cuentas independientes. En caso de que se sobrepase este n&uacute;mero, Propitech by Cirobu puede proceder a bloquear los Servicios a todas las cuentas hasta que se demuestre documentalmente la propiedad de las cuentas y del m&eacute;todo de pago.</p>
                <p>&nbsp;</p>
                <p>Asimismo, conforme a lo previsto en la Pol&iacute;tica de Privacidad, los datos bancarios del Usuario a los que Propitech by Cirobu pueda tener acceso a ra&iacute;z del pago por los Servicios mediante transferencia bancaria, tendr&aacute; la consideraci&oacute;n a todos los efectos de datos personales de los Usuarios.</p>
                <p>&nbsp;</p>
                <p>Los comprobantes de pago, facturas, boletas y/o cualquier otro documento tributario que se emita en virtud de la prestaci&oacute;n del Servicio, podr&aacute;n ser solicitados por el Usuario directamente en el Sitio Web, o bien estar&aacute;n a su disposici&oacute;n en su perfil de Usuario de que dispondr&aacute; en el Sitio Web.</p>
                <p>&nbsp;</p>
                <p><strong>6.- De la Conducta de los Usuarios.</strong></p>
                <p>&nbsp;</p>
                <p>El Usuario reconoce y acepta que no podr&aacute; autorizar a terceros para utilizar la cuenta que hubiere creado en el Sitio Web. Asimismo, no podr&aacute; ceder o transferir dicha cuenta.</p>
                <p>&nbsp;</p>
                <p><strong>7.- Derechos de Propiedad Intelectual e Industrial.</strong></p>
                <p>&nbsp;</p>
                <p>El Usuario o potencial arrendatario reconoce y acepta que todos los derechos de propiedad intelectual e industrial sobre los contenidos y/o cualesquiera otros elementos insertados en el Sitio Web (incluyendo, sin limitaci&oacute;n, marcas, logotipos, nombres comerciales, textos, im&aacute;genes, gr&aacute;ficos, dise&ntilde;os, sonidos, bases de datos, software, diagramas de flujo, presentaci&oacute;n, audio y v&iacute;deo), pertenecen exclusivamente a Propitech by Cirobu.</p>
                <p>&nbsp;</p>
                <p>Propitech by Cirobu tendr&aacute; la facultad de tomar las fotograf&iacute;as y videos de la/las propiedades del Usuario, siendo el due&ntilde;o de dichos registros visuales y/o audiovisuales. En su calidad de due&ntilde;o de dichos registros Propitech by Cirobu podr&aacute; hacer el uso que estime conveniente de dichos materiales, espec&iacute;ficamente subirlas a portales inmobiliarios, publicaciones en medios digitales, impresos u otros para su comercializaci&oacute;n. Se hace presente que todos los registros capturados por Propitech by Cirobu no pueden ser utilizados por el Usuario sin el consentimiento previo por parte de Propitech by Cirobu.</p>
                <p>&nbsp;</p>
                <p>El Usuario s&oacute;lo podr&aacute; proveer o subir im&aacute;genes o videos al Sitio Web, si &eacute;l es el due&ntilde;o de dichas im&aacute;genes y/o videos, teniendo el copyright sobre los mismos. Asimismo, el Usuario manifiesta su conformidad con que Propitech by Cirobu utilice dichas fotos y/o videos de la forma que &eacute;sta considere apropiada. El Usuario se hace completamente responsable y se obliga a dejar completamente indemne a Propitech by Cirobu por el uso de las fotos y/o videos proporcionados por &eacute;l al Sitio Web o a Propitech by Cirobu, incluyendo cualquier da&ntilde;o o perjuicio causado por ser las fotos atentorias contra la moral, discriminatorias, y cualquier otro caso semejante. Asimismo, si Propitech by Cirobu estima que las fotos y/o videos provistos no se ajustan a los est&aacute;ndares del Sitio Web, podr&aacute; bajarlas del mismo sin tener que dar raz&oacute;n de dicha acci&oacute;n al Usuario.</p>
                <p>&nbsp;</p>
                <p>Cualquier otro uso o explotaci&oacute;n de cualesquiera contenidos y/u otros elementos insertados en el Sitio Web distinto de los aqu&iacute; expresamente previstos, estar&aacute; sujeto a la autorizaci&oacute;n previa de Propitech by Cirobu.</p>
                <p><strong>&nbsp;</strong></p>
                <p><strong>8.- Protecci&oacute;n De Datos.</strong></p>
                <p>&nbsp;</p>
                <p>Los datos personales que el Usuario o potencial arrendatario proporciona por medio del Formulario de Registro o solicitud de agendamiento de visita se integrar&aacute;n en un fichero de datos personales del que es responsable Propitech by Cirobu, cuya direcci&oacute;n figura en el encabezamiento del presente documento. El env&iacute;o del Formulario de Registro o solicitud de agendamiento de visita es una manifestaci&oacute;n del consentimiento libre por parte del Usuario para que Propitech by Cirobu trate los datos en la forma descrita en estos T&eacute;rminos y Condiciones y la Pol&iacute;tica de Privacidad, la cual se entiende parte integrante de estos T&eacute;rminos y Condiciones.</p>
                <p>&nbsp;</p>
                <p><strong>9.- Garant&iacute;as prestados por la Empresa.</strong></p>
                <p><strong>&nbsp;</strong></p>
                <p>Propitech by Cirobu garantiza a los clientes arrendadores, por el plazo de un a&ntilde;o, una cobertura de hasta 6 Unidades de Fomento, por concepto de da&ntilde;os y perjuicios, provocados por:</p>
                <p>&nbsp;</p>
                <p>Adem&aacute;s, Propitech by Cirobu garantiza un monto convenio de 2 Unidades de Fomento por concepto de asesor&iacute;a en la Gesti&oacute;n de Cobranza Judicial, la cual se materializa en una reuni&oacute;n de una hora, v&iacute;a plataforma ZOOM entre el cliente, y el equipo legal que apoya a Propitech by Cirobu, con el fin de que el cliente pueda encausar de mejor forma las acciones legales Propitech by Cirobu en contra de qui&eacute;n las haya causado, sin perjuicio que Propitech by Cirobu pueda tomar las acciones legales correspondientes en contra del autor del da&ntilde;o.</p>
                <p>&nbsp;</p>
                <p><strong>10.- Exclusi&oacute;n de Garant&iacute;as y Responsabilidad.</strong></p>
                <p>&nbsp;</p>
                <p>Propitech by Cirobu no garantiza la disponibilidad y continuidad del funcionamiento del Sitio Web. En consecuencia, Propitech by Cirobu no ser&aacute; en ning&uacute;n caso responsable por cualesquiera da&ntilde;os y perjuicios que puedan derivarse de (i) la falta de disponibilidad o accesibilidad al Sitio Web; (ii) la interrupci&oacute;n en el funcionamiento del Sitio Web o fallos inform&aacute;ticos, aver&iacute;as telef&oacute;nicas, desconexiones, retrasos o bloqueos causados por deficiencias o sobrecargas en las l&iacute;neas telef&oacute;nicas, centros de datos, en el sistema de Internet o en otros sistemas electr&oacute;nicos, producidos en el curso de su funcionamiento; y (iii) otros da&ntilde;os que puedan ser causados por terceros mediante intromisiones no autorizadas ajenas al control de Propitech by Cirobu. Sin perjuicio de lo anterior, en caso que el Usuario experimente cualquier tipo de dificultad en relaci&oacute;n al funcionamiento del Sitio Web, podr&aacute; contactarse con personal de Propitech by Cirobu a trav&eacute;s del correo electr&oacute;nico <u>contacto@propitech.cl </u>. Propitech by Cirobu no garantiza la ausencia de virus ni de otros elementos en el Sitio Web introducidos por terceros ajenos a Propitech by Cirobu que puedan producir alteraciones en los sistemas f&iacute;sicos o l&oacute;gicos del Usuario o potenciales arrendatarios o en los documentos electr&oacute;nicos y ficheros almacenados en sus sistemas. En consecuencia, Propitech by Cirobu no ser&aacute; en ning&uacute;n caso responsable de cualesquiera da&ntilde;os y perjuicios de toda naturaleza que pudieran derivarse de la presencia de virus u otros elementos que puedan producir alteraciones en los sistemas f&iacute;sicos o l&oacute;gicos, documentos electr&oacute;nicos o ficheros del Usuario o potenciales arrendatarios.</p>
                <p>&nbsp;</p>
                <p>Propitech by Cirobu adopta diversas medidas de protecci&oacute;n para proteger el Sitio Web y los contenidos contra ataques inform&aacute;ticos de terceros. No obstante, Propitech by Cirobu no garantiza que terceros no autorizados no puedan conocer las condiciones, caracter&iacute;sticas y circunstancias en las cuales el Usuario accede al Sitio Web. En consecuencia, Propitech by Cirobu no ser&aacute; en ning&uacute;n caso responsable de los da&ntilde;os y perjuicios que pudieran derivarse de dicho acceso no autorizado.</p>
                <p>&nbsp;</p>
                <p>Con la suscripci&oacute;n de los presentes T&eacute;rminos y Condiciones, el Usuario o potencial arrendatario declara que mantendr&aacute; indemne frente a cualquier reclamaci&oacute;n a Propitech by Cirobu, su sociedad matriz y eventuales Filiales, directores, socios, empleados, abogados y agentes, de hechos que le sean imputables derivados del (i) incumplimiento por parte del Usuario o potencial arrendatario de cualquier disposici&oacute;n contenida en los presentes T&eacute;rminos y Condiciones o de cualquier ley o regulaci&oacute;n aplicable a los mismos; (ii) incumplimiento o violaci&oacute;n de los derechos de terceros inclusive; e (iii) incumplimiento del uso permitido del Sitio Web.</p>
                <p>&nbsp;</p>
                <p><strong>11.- Notificaciones.</strong></p>
                <p>&nbsp;</p>
                <p>Propitech by Cirobu podr&aacute; realizar las notificaciones oportunas a trav&eacute;s de una notificaci&oacute;n general en el Sitio Web, a trav&eacute;s de la direcci&oacute;n de correo electr&oacute;nico facilitada por el Usuario en el Formulario de Registro o mediante correo ordinario a la direcci&oacute;n facilitada por el Usuario en el Formulario de Registro o agendamiento de visita del potencial arrendatario. El Usuario o potencial arrendatario podr&aacute; notificar a Propitech by Cirobu a trav&eacute;s del env&iacute;o de un correo electr&oacute;nico a la direcci&oacute;n Propitech by Cirobu <a href="mailto:contacto@propitech.cl">contacto@propitech.cl</a> , o bien por medio del Contacto del Sitio Web.</p>
                <p>&nbsp;</p>
                <p><strong>12.- Cesi&oacute;n.</strong></p>
                <p>&nbsp;</p>
                <p>El Usuario o potencial arrendatario no podr&aacute; ceder sus derechos y obligaciones que emanen de los presentes T&eacute;rminos y Condiciones sin el previo consentimiento escrito de Propitech by Cirobu, el cual podr&aacute; ser solicitado a trav&eacute;s del correo electr&oacute;nico <u>contacto@propitech.cl</u>, sin que exista ninguna obligaci&oacute;n de Propitech by Cirobu de aceptar dicha solicitud. Propitech by Cirobu podr&aacute; ceder, sin necesidad de recabar el consentimiento previo del Usuario o potencial arrendatario, los presentes T&eacute;rminos y Condiciones a cualquier entidad comprendida dentro de su grupo de sociedades, en todo el mundo, as&iacute; como a cualquier persona o entidad que le suceda en el ejercicio de su negocio por cualquier t&iacute;tulo.</p>
                <p>&nbsp;</p>
                <p><strong>13.- Ley Aplicable y Jurisdicci&oacute;n,</strong></p>
                <p>&nbsp;</p>
                <p>El acceso y uso del sitio web, redes sociales y formularios electr&oacute;nicos, se regir&aacute; &iacute;ntegramente por las leyes de la Rep&uacute;blica de Chile. Por consiguiente, las visitas, as&iacute; como tambi&eacute;n los posibles contratos o transacciones que el usuario realice en la plataforma que representa el sitio web, redes sociales o formularios, as&iacute; como los efectos jur&iacute;dicos que &eacute;stas pudieran tener, quedan sometidos a las leyes y a la jurisdicci&oacute;n de los tribunales de justicia de Santiago, Rep&uacute;blica de Chile. De particular importancia resultan la aplicaci&oacute;n de la Ley N&deg; 19.628 de Protecci&oacute;n de Datos Personales y la Ley N&deg; 19.496 sobre Derechos del Consumidor. Las partes acuerdan que, conforme a la Ley de Protecci&oacute;n al Consumidor, el Usuario o potencial arrendatario (consumidor) que desee ejercer acciones legales contra Propitech by Cirobu, podr&aacute; hacerlo ante el Juzgado de Polic&iacute;a Local del (i) lugar donde se celebr&oacute; o ejecut&oacute; el acto o contrato, (ii) domicilio del proveedor, o (iii) domicilio del consumidor, a su elecci&oacute;n. Es decir, el Usuario o potencial arrendatario siempre puede elegir en cual de esos tres territorios ejercer&aacute; su acci&oacute;n.</p>
                <p>Adicionalmente, este sitio web y sus contenidos, as&iacute; como tambi&eacute;n las transacciones que se pudieran llevar a cabo en &eacute;l, est&aacute;n destinados &uacute;nicamente a personas con residencia o domiciliadas en Chile, sea que &eacute;stas sean chilenos o extranjeros.</p>
                <p>&nbsp;</p>
                <p><strong>14.- Documentos Electr&oacute;nicos.</strong></p>
                <p>&nbsp;</p>
                <p>El Usuario en su calidad de receptor manual de documentos electr&oacute;nicos, de conformidad con la Resoluci&oacute;n Exenta N&deg; 11 del 14 de febrero de 2003 del Servicio de Impuestos Internos (que estableci&oacute; el procedimiento para que contribuyentes autorizados para emitir documentos electr&oacute;nicos puedan tambi&eacute;n enviarlos por estos medios a receptores manuales), declara y acepta lo siguiente:</p>
                <p>&nbsp;</p>
                <p>Al aprobar estos T&eacute;rminos y Condiciones, el Usuario autoriza a la empresa <strong>INVERSIONES Y SERVICIOS PROFESIONALES B&amp;C SpA</strong>, rol &uacute;nico tributario n&uacute;mero 77.135.302-9, para que le sean enviados solamente por un medio electr&oacute;nico <u>los documentos tributarios que no amparan el traslado de bienes corporales muebles, ya sea v&iacute;a correo electr&oacute;nico registrado en su perfil de Usuario o mediante su publicaci&oacute;n en el sitio web www.propitech.cl.</u></p>
                <p>&nbsp;</p>
                <p>De conformidad con la normativa indicada, y en caso que el Usuario lo requiera para respaldar la informaci&oacute;n contable, &eacute;ste asume en relaci&oacute;n a dichos documentos tributarios, las siguientes obligaciones:</p>
                <p>&nbsp;</p>
                    <ul>
                        <li>Imprimir los documentos recibidos en forma electr&oacute;nica, para cada per&iacute;odo tributario, en forma inmediata a su recepci&oacute;n desde el emisor.</li>
                        <li>Imprimir el documento en el tama&ntilde;o y forma que fue generado.</li>
                        <li>Utilizar papel blanco tipo original de tama&ntilde;o m&iacute;nimo 21,5 cm x 14 cm (1/2 carta) y de tama&ntilde;o m&aacute;ximo 21,5 x 33 cm (oficio).</li>
                        <li>Imprimir en una calidad que asegure la permanencia de la legibilidad del documento durante un periodo m&iacute;nimo de seis a&ntilde;os, conforme lo establece la legislaci&oacute;n vigente sobre la materia. Esta impresi&oacute;n se har&aacute; usando impresi&oacute;n l&aacute;ser o de inyecci&oacute;n de tinta, excepto que se establezca una autorizaci&oacute;n o norma distinta al respecto.</li>
                    </ul>
                <p>&nbsp;</p>
                <p><strong>15.-</strong> <strong>COMUNICACIONES.</strong></p>
                <p><strong>INVERSIONES Y SERVICIOS PROFESIONALES B&amp;C SpA</strong> se obliga a, en caso de enviar cualquier tipo de comunicaci&oacute;n e informaci&oacute;n, incluyendo publicidad o promociones, a cualquier medio de contacto proporcionado por el Usuario, incluyendo n&uacute;meros telef&oacute;nicos o correo electr&oacute;nico, dicha comunicaci&oacute;n contendr&aacute; al menos la siguiente informaci&oacute;n:</p>
                <p><strong>a.-</strong> Identificaci&oacute;n del tipo de mensaje, dejando en claro al Usuario el tipo de informaci&oacute;n que se trata, especialmente si es un mensaje que contiene publicidad o promociones, todo lo cual figurar&aacute; en el campo de asunto del mensaje (e-mail), o bien se informar&aacute; en primer lugar (comunicaci&oacute;n telef&oacute;nica por voz o texto).</p>
                <p><strong>b.-</strong> Existencia del derecho del consumidor, reconocido por la normativa chilena, relacionado con la facultad que tiene el Usuario para solicitar el cese de este tipo de mensajes por parte de <strong>INVERSIONES Y SERVICIOS PROFESIONALES B&amp;C SpA</strong>. Al mismo tiempo, se reconoce la obligaci&oacute;n por parte de <strong>INVERSIONES Y SERVICIOS PROFESIONALES B&amp;C SpA</strong> de suspender los env&iacute;os de informaci&oacute;n en caso de recibir la solicitud por parte del Usuario.</p>
                <p><strong>c.-</strong> La garant&iacute;a de un proceso expedito, sencillo y efectivo para el caso que el Usuario quiera hacer la solicitud, para la cual el <strong>INVERSIONES Y SERVICIOS PROFESIONALES B&amp;C SpA</strong> puede requerir alg&uacute;n tipo de informaci&oacute;n previo a llevarlo a cabo.</p>
                <p><strong>d.- </strong>La reserva es de uso exclusivo para dejar de mostrar la propiedad en portales y cancelar visitas previamente agendadas. Si el propietario desiste de arrendar se deber&aacute; devolver la reserva en su totalidad al postulante, en el caso contrario, si en postulante desiste de arrendar, no tendr&aacute; devoluci&oacute;n de la reserva. Por dejar la propiedad sin visualizaci&oacute;n a otros interesados.</p>
                <p><strong>e.-</strong> En caso que se trate de publicidad o promociones provenientes de sitios externos, o de empresas, compa&ntilde;&iacute;as o marcas asociadas con <strong>INVERSIONES Y SERVICIOS PROFESIONALES B&amp;C SpA</strong>, el mensaje contendr&aacute; la informaci&oacute;n necesaria para identificar al anunciante, incluyendo su denominaci&oacute;n comercial si la tuviera.</p>
                <p>Las promociones que se ofrezcan por medio de este Sitio Web, v&iacute;a correo electr&oacute;nico u otro medio de comunicaci&oacute;n no son necesariamente las mismas que ofrezcan otros canales de venta utilizados por las empresas, tales como locales f&iacute;sicos, anuncios por TV o radio, cat&aacute;logos u otros, a menos que se se&ntilde;ale expresamente en este sitio o en la publicidad que realicen las empresas de cada promoci&oacute;n.</p>
                <p>&nbsp;</p>
            </div>
        </div>
    </div>
</section>
@endsection
@section('jss')

@endsection