<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ContratoArriendo extends Model
{
    protected $table = 'contratos_arriendos';
    protected $primaryKey = 'idContratoArriendo';
    protected $fillable = [
        'idTipoContrato',
        'nombreContrato',
        'desde',
        'hasta',
        'tiempoContrato',
        'diaNotificacionFinContrato',
        'diaPago',
        'idUsuarioPropietario',
        'idUsuarioArrendatario',
        'idUsuarioCodeudor',
        'idPropiedad',
        'idEstado',
        'nota',
        'imagenFirma',
        'firmaBase64',
        'idCorredor',
        'idMoneda',
        'arriendoMensual',
        'garantia',
        'idTiempoPagoGarantia',
        'reajuste',
        'reajustePesos',
        'rutArrendatario',
        'nombreArrendatario',
        'apellidoArrendatario',
        'nacionalidadArrendatario',
        'estadoCivilArrendatario',
        'direccionArrendatario',
        'nombreComunaArrendatario',
        'nombreRegionArrendatario',
        'correoArrendatario',
        'numeroTelefonoArrendatario',
        'rutPropietario',
        'nombrePropietario',
        'apellidoPropietario',
        'direccionPropietario',
        'correoPropietario',
        'numeroPropietario',
        'rutCodeudor',
        'nombreCodeudor',
        'apellidoCodeudor',
        'nacionalidadCodeudor',
        'telefonoCodeudor',
        'correoCodeudor',
        'direccionPropiedad',
        'nombreComunaPropiedad',
        'nombreRegionPropiedad',
        'block',
        'rolPropiedad',
        'maximoHabitantes',
        'idSucursal',
        'tokenContratoServicio',
        'idMetodoPago',
        'idNotaria',
        'fechaCompromiso',
        'primerPago',
        'cantidadGarantias',
        'idMandato',
        'creadoPor',
        'imagenFirmaVendedor',
        'fechaFirmaVendedor',
        'imagenFirmaArrendatario',
        'fechaFirmaArrendatario',
        'imagenFirmaCodeudor',
        'fechaFirmaCodeudor',
        'tokenContratoArriendo',
        'numeroDeCertificado',
        'notarizado',
        'descuentoPesosComision',
        'descuentoPorcentajeComision',
        'fechaTerminoContrato',
        'textoGarantia',
        'idRenovacion',
        'fechaSalidaArrendatario',
        'motivoSalida',
        'prohibiciones',
        'renovacionAutomatica',
        'created_at',
        'updated_at'
    ];
}
